import os

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', None)
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', None)
AWS_DEFAULT_REGION = os.environ.get('AWS_DEFAULT_REGION', None)
TWITTER_CONSUMER_KEY=os.environ["TWITTER_CONSUMER_KEY"]
TWITTER_CONSUMER_SECRET=os.environ["TWITTER_CONSUMER_SECRET"]
TWITTER_ACCESS_KEY=os.environ["TWITTER_ACCESS_KEY"]
TWITTER_ACCESS_SECRET=os.environ["TWITTER_ACCESS_SECRET"]